alter session set sql_trace=true;

DROP TABLE FIGIS_GIS.SOURCE_LAYER;
DROP TABLE FIGIS_GIS.TARGET_LAYER;
DROP TABLE FIGIS_GIS.MASK_LAYER;

COMMIT;

CREATE TABLE FIGIS_GIS.SOURCE_LAYER (
    id NUMBER PRIMARY KEY,
    code VARCHAR2(32),
    th_shape MDSYS.SDO_GEOMETRY);

CREATE TABLE FIGIS_GIS.TARGET_LAYER (
    id NUMBER PRIMARY KEY,
    code VARCHAR2(32),
    th_shape MDSYS.SDO_GEOMETRY);

CREATE TABLE FIGIS_GIS.MASK_LAYER (
    id NUMBER PRIMARY KEY,
    code VARCHAR2(32),
    th_shape MDSYS.SDO_GEOMETRY);

COMMIT;

DELETE FROM all_sdo_geom_metadata WHERE TABLE_NAME LIKE '%SOURCE%';
DELETE FROM all_sdo_geom_metadata WHERE TABLE_NAME LIKE '%TARGET%';
DELETE FROM all_sdo_geom_metadata WHERE TABLE_NAME LIKE '%MASK%';

INSERT INTO ALL_SDO_GEOM_METADATA VALUES (
            'FIGIS_GIS',
            'SOURCE_LAYER',
            'TH_SHAPE',
            MDSYS.SDO_DIM_ARRAY(
                MDSYS.SDO_DIM_ELEMENT('LONGITUDE',0,11,0.005),
                MDSYS.SDO_DIM_ELEMENT('LATITUDE',0,4,0.005)
            ),
            4326
                );

INSERT INTO ALL_SDO_GEOM_METADATA VALUES (
            'FIGIS_GIS',
            'TARGET_LAYER',
            'TH_SHAPE',
            MDSYS.SDO_DIM_ARRAY(
                MDSYS.SDO_DIM_ELEMENT('LONGITUDE',0,11,0.005),
                MDSYS.SDO_DIM_ELEMENT('LATITUDE',0,4,0.005)
            ),
            4326
                );

INSERT INTO ALL_SDO_GEOM_METADATA VALUES (
            'FIGIS_GIS',
            'MASK_LAYER',
            'TH_SHAPE',
            MDSYS.SDO_DIM_ARRAY(
                MDSYS.SDO_DIM_ELEMENT('LONGITUDE',0,11,0.005),
                MDSYS.SDO_DIM_ELEMENT('LATITUDE',0,4,0.005)
            ),
            4326
                );

COMMIT;


INSERT INTO FIGIS_GIS.SOURCE_LAYER VALUES(
    1, -- feature_id
    'sa', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(2,0, 2,3, 5,3, 5,0, 2,0)
    )
);

INSERT INTO FIGIS_GIS.SOURCE_LAYER VALUES(
    2, -- feature_id
    'sb', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(7,0, 7,3, 8.5,3, 8.5,0, 7,0)
    )
);

INSERT INTO FIGIS_GIS.TARGET_LAYER VALUES(
    1, -- feature_id
    'ta', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(0,0, 0,2, 4,2, 4,0, 0,0)
    )
);

INSERT INTO FIGIS_GIS.TARGET_LAYER VALUES(
    2, -- feature_id
    'tb', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(4,2, 4,3, 8,3, 8,2, 4,2)
    )
);

INSERT INTO FIGIS_GIS.TARGET_LAYER VALUES(
    3, -- feature_id
    'sc', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(5,0, 5,1, 6,1, 6,0, 5,0)
    )
);

INSERT INTO FIGIS_GIS.TARGET_LAYER VALUES(
    4, -- feature_id
    'td', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(7,0, 7,1, 8,1, 8,0, 7,0)
    )
);


INSERT INTO FIGIS_GIS.MASK_LAYER VALUES(
    1, -- feature_id
    'ma', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(3,2, 3,3, 6,3, 6,2, 3,2)
    )
);
INSERT INTO FIGIS_GIS.MASK_LAYER VALUES(
    2, -- feature_id
    'mb', -- code
    MDSYS.SDO_GEOMETRY(
       2003, 4326, NULL,
       MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
       MDSYS.SDO_ORDINATE_ARRAY(3,0, 3,1, 9,1, 9,0, 3,0)
    )
);

CREATE INDEX "FIGIS_GIS"."SOURCE_LAYER_IDX" ON "FIGIS_GIS"."SOURCE_LAYER" ("TH_SHAPE") INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_DML_BATCH_SIZE=1');
CREATE INDEX "FIGIS_GIS"."TARGET_LAYER_IDX" ON "FIGIS_GIS"."TARGET_LAYER" ("TH_SHAPE") INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_DML_BATCH_SIZE=1');
CREATE INDEX "FIGIS_GIS"."MASK_LAYER_IDX" ON "FIGIS_GIS"."MASK_LAYER" ("TH_SHAPE") INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_DML_BATCH_SIZE=1');


COMMIT;
